// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU27_WcMezrFLYhdLauQB_n4FKb2WUm94',
    appId: '1:303643350521:web:0047b52ff233a5e52a5928',
    messagingSenderId: '303643350521',
    projectId: 'flutter-day-26',
    authDomain: 'flutter-day-26.firebaseapp.com',
    databaseURL: 'https://flutter-day-26-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-day-26.appspot.com',
    measurementId: 'G-ZQQWS06FWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjzd_ALf_8zI1SSSdU0TwZwnUIihn3O20',
    appId: '1:303643350521:android:4e2b8d3049417ef22a5928',
    messagingSenderId: '303643350521',
    projectId: 'flutter-day-26',
    databaseURL: 'https://flutter-day-26-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-day-26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJsarIfnkgJYNwnddHfBvnsxVUFpVej7U',
    appId: '1:303643350521:ios:d0364180faddbc422a5928',
    messagingSenderId: '303643350521',
    projectId: 'flutter-day-26',
    databaseURL: 'https://flutter-day-26-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-day-26.appspot.com',
    iosBundleId: 'com.example.flutterDay52',
  );
}
